title: Mighty English
description: Курсы английского языка
url: ""

livereload: true

exclude:
  - package.json
  - package-lock.json
  - node_modules
  - src
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - "*.gemspec"
  - .pages.yml

collections:
  skills:
    output: true
  about:
    output: true

sass:
  sass_dir: _sass
  style: compressed
