# Site settings
title: Mighty English
description: Курсы английского языка
# baseurl: "mightyenglish" # the subpath of your site, e.g. /blog
url: ""
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# Header settings
header_title_eng: Mighty English
header_title_ru: Мощный английский
header_title_descr: Авторский курс английского языка Рудольфа Ладнера

email: ladnerrudolf@mail.ru

form_post_link: https://formspree.io/ladnerrudolf@mail.ru

social_link__tel: tel:+79518943056
social_link__email: mailto:ladnerrudolf@mail.ru
social_link__vk: https://vk.com/ladnerrudolf
social_link__whatsapp: https://wa.me/79518943056
social_link__telegram: https://t.me/mighty_english

footer_text: Авторский курс английского языка "Mighty English"

# Google-analytics
google-analytics:
  id: ""

livereload: true

exclude: ["package.json", "src", "node_modules"]

collections:
  skills:
    output: true
  about:
    output: true
