site_title: Mighty English
header_subtitle: Авторский курс английского языка Рудольфа Ладнера
description: Курсы английского языка
footer_text: Авторский курс английского языка "Mighty English"

email: ladnerrudolf@mail.ru
phone: "+79518943056"
vk: https://vk.com/ladnerrudolf
whatsapp: https://wa.me/message/VUT7GGZ2KKXDB1
telegram: https://t.me/mighty_english

formspree_url: https://formspree.io/ladnerrudolf@mail.ru
